[workspace.package]
edition = "2024"

[workspace]
resolver = "3"
members = [
    "crates/vulkan-renderer",
    "crates/renderer",

    "crates/engine",
    "crates/plugin-interface",
    "crates/test-plugin",
    "crates/math",
    "crates/window",
    "crates/editor",
]

[workspace.dependencies]
# Local crates
vulkan-renderer = { version = "0.1.0", path = "./crates/vulkan-renderer" }

engine131 = { version = "0.1.0", path = "./crates/engine" }
plugin-interface = { version = "0.1.0", path = "./crates/plugin-interface" }
test-plugin = { version = "0.1.0", path = "./crates/test-plugin" }
math131 = { version = "0.1.0", path = "./crates/math", features = [ "SIMD" ] }
renderer131 = { version = "0.1.0", path = "./crates/renderer" }
window131 = { version = "0.1.0", path = "./crates/window", features = [ "GLFW" ] }

editor131 = { version = "0.1.0", path = "./crates/editor" }

# External libraries (dependencies)
ash = "0.38.0"
libloading = "0.9.0"
thiserror = "2.0.18"
