[workspace.package]
edition = "2024"

[workspace]
resolver = "3"
members = [
    "crates/vulkan-renderer",
    "crates/renderer",

    "crates/engine",
    "crates/math",
    "crates/window",
    "crates/editor",
]

[workspace.dependencies]
# Built-in plugins
vulkan-renderer = { version = "0.1.0", path = "./crates/vulkan-renderer", features = [ "GLFW" ] }

# Local crates
engine131 = { version = "0.1.0", path = "./crates/engine" }
math131 = { version = "0.1.0", path = "./crates/math", features = [ "SIMD" ] }
renderer131 = { version = "0.1.0", path = "./crates/renderer" }
window131 = { version = "0.1.0", path = "./crates/window", features = [ "GLFW" ] }

editor131 = { version = "0.1.0", path = "./crates/editor" }

# External libraries (dependencies)
ash = { version = "0.38.0", features = [ "debug", "linked" ] }
serde = { version = "1.0.228", default-features = true, features = [ "derive" ] }
thiserror = "2.0.18"
toml = "1.1.4"
