[package]
name = "vulkan-renderer"
version = "0.1.0"
edition.workspace = true

[dependencies]
renderer131.workspace = true
window131.workspace = true

ash.workspace = true
thiserror.workspace = true

raw-window-handle = { version = "0.6.2", optional = true }

[features]
GLFW = [ "raw-window-handle" ]

