// @generated by build.rs — do not edit by hand

pub static DEFAULT_VERT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/shaders/default.vert.Vulkan"));
pub static DEFAULT_FRAG: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/shaders/default.frag.Vulkan"));

